import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import FooterSec from "@/components/shared/Footer";
import { Hind_Siliguri } from "next/font/google";

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["300","400","500","600","700"],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hindSiliguri.className} antialiased bg-[#F5F7F6]`}
      >
        <div>
          <Navbar></Navbar>
        </div>
        <div className="bg-base-00">
          {children}
        </div>
        <div>
          <FooterSec></FooterSec>
        </div>
      </body>
    </html>
  );
}
